# Generated by Django 2.1 on 2019-09-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=200, unique=True)),
                ('vacant', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theatre_cap', models.SmallIntegerField(default=0)),
                ('classroom_cap', models.SmallIntegerField(default=0)),
                ('ushape_cap', models.SmallIntegerField(default=0)),
                ('reception_cap', models.SmallIntegerField(default=0)),
                ('width_in_meters', models.SmallIntegerField(default=0, verbose_name='width')),
                ('length_in_meters', models.SmallIntegerField(default=0, verbose_name='length')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Pbguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied'), ('C', 'Cancelled')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_guests', models.SmallIntegerField()),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedAccomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.SmallIntegerField()),
                ('accomodation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.AccomodationType')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_guest_id', to='reservations.Pbguser')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_made_by', to='reservations.Pbguser')),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='ConferenceReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation')),
                ('conference_hall_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.ConferenceHall')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_guest_id', to='reservations.Pbguser')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_made_by', to='reservations.Pbguser')),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='SecurityReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_guest_id', to='reservations.Pbguser')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_made_by', to='reservations.Pbguser')),
                ('security_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SecurityService')),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='TransportReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation')),
                ('car_type', models.CharField(choices=[('A', 'Armored'), ('N', 'Normal')], default='N', max_length=1)),
                ('district', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('purpose_of_visit', models.CharField(max_length=200)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_guest_id', to='reservations.Pbguser')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_made_by', to='reservations.Pbguser')),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='accomodation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.AccomodationType'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Branch'),
        ),
        migrations.AddField(
            model_name='reservedaccomodation',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.AccomodationReservation'),
        ),
    ]
