# Generated by Django 2.2.3 on 2019-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20190902_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencereservation',
            name='number_of_guests',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
