# Generated by Django 2.2.3 on 2019-09-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_conferencereservation_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedaccomodation',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='accomodationreservation',
            name='number_of_guests',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityreservation',
            name='number_of_guests',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportreservation',
            name='number_of_guests',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
