# Generated by Django 2.2.3 on 2019-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20190903_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbguser',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
