# Generated by Django 2.2.3 on 2019-09-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20190903_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbguser',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
