# Generated by Django 2.2.3 on 2019-09-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20190903_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbguser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
    ]
