# Generated by Django 2.2.3 on 2019-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20190903_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='accomodation_type_id',
            new_name='accomodation_type',
        ),
        migrations.RenameField(
            model_name='reservedaccomodation',
            old_name='accomodation_type_id',
            new_name='accomodation_type',
        ),
        migrations.AlterField(
            model_name='pbguser',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
