# Generated by Django 2.2.3 on 2019-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20190904_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
