# Generated by Django 2.2.3 on 2019-09-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_accomodation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='price',
        ),
        migrations.AddField(
            model_name='accomodationtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
