# Generated by Django 2.2.3 on 2019-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20190904_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationreservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied'), ('C', 'Cancelled')], max_length=1),
        ),
        migrations.AlterField(
            model_name='conferencereservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied'), ('C', 'Cancelled')], max_length=1),
        ),
        migrations.AlterField(
            model_name='securityreservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied'), ('C', 'Cancelled')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied'), ('C', 'Cancelled')], max_length=1),
        ),
    ]
