# Generated by Django 2.2.3 on 2019-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20190905_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationreservation',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='conferencereservation',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='securityreservation',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
