# Generated by Django 2.2.3 on 2019-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20190905_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationreservation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conferencereservation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='securityreservation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
